# clixoer container along with postgres and elasticsearch containers

version: '2'

services:
  #elasticsearch container
  elastic_db:
    image: elasticsearch:6.8.8
    container_name: elastic_db_latest
    restart: always
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data

  #postgres container
  psql_db:
    image: postgres:10-alpine
    container_name: psql_latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pg_pwd 
    volumes:
      - ./psql_data:/var/lib/postgresql/data/
 
  # Clixoer container
  clixoer:
    image: clixoer_2021:v2
    container_name: clixoer_v2
    restart: always
    depends_on: 
      - elastic_db
      - psql_db
    environment:
      - TERM=xterm
    hostname: <host name>
    ports:
      - "80:80"             #http
      - "443:443"           #https
      - "8022:22"           #ssh
      - "8025:25"           #smtp
      - "8143:143"          #g-imap
      - "8587:587"          #g-smtp
      - "8000:8000"         #dev
      - "8017:27017"        #mongodb
      - "8080:8080"         #qbank
      - "5555:5555"         #celery-flower
      #- "8432:5432"         #postgres
      #- "9200:9201"         #elasticsearch
    volumes:
      #Change the path of the folder according to the folder path
      - ./data:/data
      - ./code:/home/docker/code
